apiVersion: v1
kind: Pod
metadata:
  name: mangoapp
  labels:
    app: mangoapp
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: myvol
    configMap: 
      name: appindex 

---
apiVersion: v1
kind: Service
metadata:
  name: mangoapp-svc
spec:
  type: NodePort
  selector:
    app: mangoapp
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30125

