apiVersion: v1
data:
  index.html: |
    <h1> Hello, this is mango application </h1>
    asdfmadsklfasd'fads
    f
    asdf
    asd
    f
    adsf
    a
    sdf
    asd
    fasdkfaklsdjfkl;adsjfkl;jdskfjasdjfasdf
    asdf
    asdfl;asdfklasdkfjadsfasd
    fsd
    f
kind: ConfigMap
metadata:
  name: appindex
