apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 3
  selector:
    matchLabels:
     app: mango
  template:
    metadata:
      labels:
        app: mango
    spec:
      containers:
      - name: con1
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc
spec:
  type: NodePort
  selector:
    app: mango
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30123
