apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 1
  selector:
    matchLabels:
     app: mango
  template:
    metadata:
      labels:
        app: mango
    spec:
      initContainers:
      - name: icon
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c","echo '<h1> Hello from, initContainers index file</h1>' > /app/index.html"]
        volumeMounts:
        - name: myvol
          mountPath: /app
      containers:
      - name: con1
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myvol
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: myvol
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc
spec:
  type: NodePort
  selector:
    app: mango
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30123
