apiVersion: apps/v1
kind: Deployment
metadata:
  name: deplivexec
spec:
  replicas: 1
  selector:
    matchLabels:
     app: mango
  template:
    metadata:
      labels:
        app: mango
    spec:
      containers:
      - name: con1
        image: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - cat
            - /usr/share/nginx/html/index.html
          initialDelaySeconds: 10
          periodSeconds: 5
      - name: con2
        image: tomcat:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc
spec:
  type: NodePort
  selector:
    app: mango
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30123
