apiVersion: v1
kind: Pod
metadata:
  namespace: devops
  name: newpod
  labels:
    app: myapp
    env: dev
spec:
  serviceAccount: robo
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"

