apiVersion: v1
kind: Pod
metadata:
  name: newpod
  labels:
    app: myapp
    env: dev
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /app
  volumes:
  - name: myvol
    secret:
      secretName: myapp-crt
